baseURL = 'www.jameschua.net'
languageCode = 'en-us'
theme = 'nightfall'


[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
  [params.author]
    name = "James Chua"  # Website and RSS feed author
    email = "email@example.com"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/thejaminator"
